# Generated by Django 4.2.7 on 2023-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0004_remove_pokemoncard_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='card_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('fighting', 'Fighting'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy'), ('dragon', 'Dragon'), ('normal', 'Normal'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('bug', 'Bug'), ('rock', 'Rock'), ('ground', 'Ground'), ('poison', 'Poison'), ('flying', 'Flying')], default='none', max_length=255),
        ),
    ]
